consumption <- read.table("./data/household_power_consumption.txt", header = TRUE, sep = ";")
consumption[,1] <- as.Date(consumption[,1], "%d/%m/%Y")
consumption <- consumption[consumption$Date >= "2007-02-01" & consumption$Date < "2007-02-03",]
consumption[,3] <- as.numeric(consumption[,3])
consumption[,4] <- as.numeric(consumption[,4])
consumption[,5] <- as.numeric(consumption[,5])
consumption[,6] <- as.numeric(consumption[,6])
consumption[,7] <- as.numeric(consumption[,7])
consumption[,8] <- as.numeric(consumption[,8])
DateTime <- strptime(paste(consumption[,1], consumption[,2]), "%Y-%m-%d %H:%M:%S")
con <- cbind(DateTime, consumption)
plot(con$DateTime, con$Sub_metering_1, cex = 0, ylab = "Global Active Power (kilowatts)", xlab = "", main = "Global Active Power")
with(lines(con$DateTime, con$Sub_metering_1))   
with(lines(con$DateTime, con$Sub_metering_2))
with(lines(con$DateTime, con$Sub_metering_3))	
legend("topright", lty = 1, legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.copy(png, "plot3.png")
dev.off()